#tag Module
Protected Module SpreadsheetCodeGen
	#tag Method, Flags = &h0, Description = 456D697420586F6A6F20736F7572636520666F722061206D6574686F6420746861742072656275696C64732074686520776F726B626F6F6B207669612074686520666C75656E7420617574686F72696E67204150493B2072657475726E732074686520636F6D706C6574652046756E6374696F6E20617320746578742E0A
		Function Generate(wb As XLSXWorkbook, methodName As String = "BuildWorkbook") As String
		  ' Emit Xojo source for a method that rebuilds `wb` using the fluent authoring
		  ' API (XLSXWorkbook.AddSheet + XLSXSheet.Put* + XLSXCell style mutators). The
		  ' returned text is a complete Function the caller can paste into a project.
		  If wb Is Nil Then Return ""
		  Var L() As String
		  L.Add "Public Function " + methodName + "() As XLSXWorkbook"
		  L.Add "  // Generated by SpreadsheetCodeGen from " + wb.SourceName + "."
		  L.Add "  // Edit the data below, then e.g.: SpreadsheetWriter.Save(" + methodName + "(), destFile)"
		  L.Add "  // Not reproduced: per-edge (mixed) borders, rich text, Excel Tables, charts/images."
		  L.Add "  Var wb As New XLSXWorkbook(" + XojoStr(wb.SourceName) + ")"
		  L.Add ""
		  For s As Integer = 1 To wb.SheetCount
		    Var sheet As XLSXSheet = wb.SheetAtRaw(s)
		    Var v As String = "ws" + Str(s)
		    L.Add "  // --- Sheet: " + sheet.Name + " ---"
		    L.Add "  Var " + v + " As XLSXSheet = wb.AddSheet(" + XojoStr(sheet.Name) + ")"
		    For r As Integer = 1 To sheet.RowCount
		      For c As Integer = 1 To sheet.ColCount
		        Var line As String = EmitCell(v, sheet, wb.Styles, r, c)
		        If line <> "" Then L.Add "  " + line
		      Next
		    Next
		    For c As Integer = 1 To sheet.ColCount
		      Var w As Double = sheet.ColumnWidthRaw(c)
		      If w > 0 Then L.Add "  " + v + ".SetColumnWidth(" + Str(XLSXHelpers.ToPublicIndex(c)) + ", " + Str(w) + ")"
		    Next
		    For i As Integer = 0 To sheet.MergedRangeCount - 1
		      Var rng As XLSXCellRange = sheet.MergedRangeAt(i)
		      If rng Is Nil Then Continue
		      L.Add "  " + v + ".AddMergedRange(" + Str(XLSXHelpers.ToPublicIndex(rng.FirstRowRaw)) + ", " + Str(XLSXHelpers.ToPublicIndex(rng.FirstColRaw)) + ", " + Str(XLSXHelpers.ToPublicIndex(rng.LastRowRaw)) + ", " + Str(XLSXHelpers.ToPublicIndex(rng.LastColRaw)) + ")"
		    Next
		    L.Add ""
		  Next
		  L.Add "  Return wb"
		  L.Add "End Function"
		  Return String.FromArray(L, EndOfLine)
		End Function
	#tag EndMethod

	#tag Method, Flags = &h21
		Function EmitCell(v As String, sheet As XLSXSheet, styles As XLSXStyles, r As Integer, c As Integer) As String
		  ' One Put* statement for the cell at (r,c), or empty for a cell that needs none.
		  Var cell As XLSXCell = sheet.CellAtRaw(r, c)
		  If cell.IsEmpty Then Return ""
		  If sheet.IsCellMergedFollowerRaw(r, c) Then Return ""
		  Var pos As String = "(" + Str(XLSXHelpers.ToPublicIndex(r)) + ", " + Str(XLSXHelpers.ToPublicIndex(c)) + ", "
		  Var stmt As String
		  Select Case cell.eType
		  Case XLSXEnums.eCellType.Str, XLSXEnums.eCellType.ErrorVal
		    stmt = v + ".PutText" + pos + XojoStr(cell.RawString) + ")"
		  Case XLSXEnums.eCellType.Bool
		    stmt = v + ".PutBool" + pos + If(cell.BooleanValue, "True", "False") + ")"
		  Case XLSXEnums.eCellType.DateValue
		    Var dcode As String = XLSXHelpers.WriteFormatCode(cell, styles)
		    stmt = v + ".PutNumber" + pos + Str(cell.NumberValue) + ").Format(" + XojoStr(dcode) + ")"
		  Case XLSXEnums.eCellType.FormulaCached
		    If cell.HasFormula Then
		      stmt = v + ".PutFormulaA1" + pos + XojoStr(cell.Formula) + ")"
		    Else
		      stmt = v + ".PutNumber" + pos + Str(cell.NumberValue) + ")"
		    End If
		  Else
		    stmt = v + ".PutNumber" + pos + Str(cell.NumberValue) + ")"
		  End Select
		  ' Number format (numeric / formula cells only; dates handled above).
		  If cell.eType = XLSXEnums.eCellType.Number Or cell.eType = XLSXEnums.eCellType.FormulaCached Then
		    Var code As String = XLSXHelpers.EffectiveFormatCode(cell, styles)
		    If code <> "" And code <> "General" Then
		      If code = "#,##0.00" Then
		        stmt = stmt + ".Money"
		      Else
		        stmt = stmt + ".Format(" + XojoStr(code) + ")"
		      End If
		    End If
		  End If
		  stmt = stmt + StyleChain(cell, styles)
		  Return stmt
		End Function
	#tag EndMethod

	#tag Method, Flags = &h21
		Function StyleChain(cell As XLSXCell, styles As XLSXStyles) As String
		  ' The fluent style mutators (.Bold.Italic…) for a cell's resolved style.
		  Var st As XLSXCellStyle = cell.ResolvedStyle(styles)
		  If st Is Nil Or st.IsDefault Then Return ""
		  Var s As String
		  If st.Bold Then s = s + ".Bold"
		  If st.Italic Then s = s + ".Italic"
		  If st.Underline Then s = s + ".Underline"
		  If st.HasBackground Then s = s + ".BackColor(" + ColorLit(st.BackgroundColor) + ")"
		  If st.HasFontColor Then s = s + ".FontColor(" + ColorLit(st.FontColor) + ")"
		  If st.FontName <> "" Then s = s + ".FontFace(" + XojoStr(st.FontName) + ")"
		  If st.FontSize > 0 Then s = s + ".FontSize(" + Str(st.FontSize) + ")"
		  If st.AlignH <> XLSXEnums.eAlignH.General Then s = s + ".Align(" + AlignLit(st.AlignH) + ")"
		  ' Borders: only the uniform (all four edges equal) case is expressible via .Border.
		  If st.HasAnyBorder Then
		    If st.BorderLeft = st.BorderRight And st.BorderRight = st.BorderTop And st.BorderTop = st.BorderBottom Then
		      s = s + ".Border(" + BorderLit(st.BorderLeft) + If(st.HasBorderColor, ", " + ColorLit(st.BorderColor), "") + ")"
		    End If
		  End If
		  Return s
		End Function
	#tag EndMethod

	#tag Method, Flags = &h21
		Function XojoStr(sIn As String) As String
		  ' A Xojo string literal for sIn: wrapped in quotes, internal quotes doubled.
		  Var q As String = """"
		  Return q + sIn.ReplaceAll(q, q + q) + q
		End Function
	#tag EndMethod

	#tag Method, Flags = &h21
		Function ColorLit(c As Color) As String
		  Return "&c" + Pad2(c.Red) + Pad2(c.Green) + Pad2(c.Blue)
		End Function
	#tag EndMethod

	#tag Method, Flags = &h21
		Function Pad2(v As Integer) As String
		  Var h As String = Hex(v)
		  If h.Length < 2 Then h = "0" + h
		  Return h
		End Function
	#tag EndMethod

	#tag Method, Flags = &h21
		Function AlignLit(h As XLSXEnums.eAlignH) As String
		  Select Case h
		  Case XLSXEnums.eAlignH.Left
		    Return "XLSXEnums.eAlignH.Left"
		  Case XLSXEnums.eAlignH.Center
		    Return "XLSXEnums.eAlignH.Center"
		  Case XLSXEnums.eAlignH.Right
		    Return "XLSXEnums.eAlignH.Right"
		  End Select
		  Return "XLSXEnums.eAlignH.General"
		End Function
	#tag EndMethod

	#tag Method, Flags = &h21
		Function BorderLit(b As XLSXEnums.eBorderStyle) As String
		  Select Case b
		  Case XLSXEnums.eBorderStyle.Thin
		    Return "XLSXEnums.eBorderStyle.Thin"
		  Case XLSXEnums.eBorderStyle.Medium
		    Return "XLSXEnums.eBorderStyle.Medium"
		  Case XLSXEnums.eBorderStyle.Thick
		    Return "XLSXEnums.eBorderStyle.Thick"
		  End Select
		  Return "XLSXEnums.eBorderStyle.None"
		End Function
	#tag EndMethod

	#tag Note, Name = About
		Generates Xojo source that rebuilds a workbook using the fluent authoring API.
		
		Design a template in Excel / LibreOffice (headers, styles, formulas, column
		widths, merges), open it in the app, and SpreadsheetCodeGen.Generate(wb)
		returns a ready-to-paste Function that reproduces it with XLSXWorkbook.AddSheet
		+ XLSXSheet.Put* + the XLSXCell style mutators. Fill in the real data and call
		SpreadsheetWriter.Save on the result.
		
		Reproduced: text / number / money / date / bool / formula (A1) cells, number
		formats, bold/italic/underline, fill + font colour, font name/size, horizontal
		alignment, uniform borders, column widths, merged ranges.
		Not reproduced: per-edge (mixed) borders, rich text, Excel Table overlays,
		charts / images, conditional formatting.
	#tag EndNote

	#tag ViewBehavior
	#tag EndViewBehavior
End Module
#tag EndModule
